export default [
  {
    heroName: 'Abaddon',
    race1: 'Undead',
    race1Icon: 'https://i.imgur.com/jdIK8RD.png',
    race1Ability: 'Horror',
    race1lvl1: '(2) Undead: Decrease all enemy units armor by 5.',
    race1lvl2: '(4) Undead: Decrease all enemy units armor by an additional 7.',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Knight',
    heroClass1Ability: 'Divine Protection',
    heroClasslvl1: '(2) Knights: 25% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClasslvl2: '(4) Knights: 35% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClasslvl3: '(6) Knights: 45% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClass1Icon: 'https://i.imgur.com/XTsv70x.png',
    ability1Icon: 'https://i.imgur.com/qCmHCZP.png',
    ability1Name: 'Aphotic Shield',
    ability1Target: 'Target: Allied Units',
    ability1Duration: 'Duration: 10',
    ability1Radius: 'Radius: 400',
    ability1Damage: 'Damage: 100/150/200',
    ability1Cooldown: 'Cooldown: 12',
    ability1Description: 'Summons dark energies around an allied unit, creating a shield that absorbs 100/150/200 damage before expiring. When the shield is destroyed it will burst and deal damage equal to the amount it could absorb to an area around it.',
    ability2Icon: '',
    ability2Name: '',
    cost: '3',
    portrait: 'https://i.imgur.com/vdiLnX1.png',
    rank1: 'https://i.imgur.com/cwUZfVV.jpg',
    number: 1
  },
  {
    heroName: 'Alchemist',
    race1: 'Goblin',
    race1Icon: 'https://i.imgur.com/e2CyWql.png',
    race1Ability: 'Nanobots',
    race1lvl1: '(3) Goblins: Increase Armor and HP Regen by 15 for a random ally',
    race1lvl2: '(6) Goblins: Increase Armor and HP Regen by 15 for all Goblins',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Warlock',
    heroClass1Ability: 'Life Steal',
    heroClasslvl1: '(3) Warlocks: All allies gain 15% lifesteal',
    heroClasslvl2: '(6) Warlocks: All allies gain an additional 25% lifesteal',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/OngJXn3.png',
    ability1Icon: 'https://i.imgur.com/ucq7laI.png',
    ability1Name: 'Acid Spray',
    ability1DmgType: 'Type: Physical',
    ability1Target: 'Target: AOE',
    ability1Duration: 'Duration: 10',
    ability1Radius: 'Radius: 400',
    ability1Damage: 'Damage: 15/25/35 per second',
    ability1Cooldown: 'Cooldown: 10',
    ability1Description: 'Alchemist sprays high-pressure acid across a target area. Enemy units who step across the contaminated terrain take damage per second and have their armor reduced by 5/8/11.',
    ability2Icon: '',
    ability2Name: '',
    cost: '4',
    portrait: 'https://i.imgur.com/ewA7FAM.png',
    rank1: 'https://i.imgur.com/zYytjGL.png',
    number: 2
  },
  {
    heroName: 'Anti Mage',
    race1: 'Elf',
    race1Icon: 'https://i.imgur.com/Wy9ES4n.png',
    race1Ability: 'Evasion',
    race1lvl1: '(3) Elves: All Elves gain 25% evasion from incoming attacks',
    race1lvl2: '(6) Elves: All Elves gain an additional 25% evasions from incoming attacks',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Demon Hunter',
    heroClass1Ability: 'Soul Split',
    heroClasslvl1: '(1) Demon Hunter: Enemey Demons no longer gain the Fel Power ability bonus',
    heroClasslvl2: '(2) Demon Hunters: All ally Demons keep the Fel Power bonus',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/9O3YD2y.png',
    ability1Icon: 'https://i.imgur.com/H0nAs3X.png',
    ability1Name: 'Mana Break',
    ability1DmgType: 'Type: Physical',
    ability1Target: 'Target: Enemy Units',
    ability1Damage: 'Damage: 30/60/90 Mana Per Hit',
    ability1Cooldown: 'Aura',
    ability1Description: "Burns an opponent's mana on each attack. Mana break deal's 50% of the mana burned as damage to the target. ",
    ability2Icon: '',
    ability2Name: '',
    cost: '1',
    portrait: 'https://i.imgur.com/A9OCs2j.png',
    rank1: 'https://i.imgur.com/wt40P7O.png',
    number: 3
  },
  {
    heroName: 'Axe',
    race1: 'Orc',
    race1Icon: 'https://i.imgur.com/lrXutiw.png',
    race1Ability: 'Battle Hardened',
    race1lvl1: '(2) Orcs: All Orcs gain 250 max HP',
    race1lvl2: '(4) Orcs: All Orcs gain an additional 350 max hp',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Warrior',
    heroClass1Ability: 'Fortified Armor',
    heroClasslvl1: '(3) Warriors: All Warriors gain 7 armor',
    heroClasslvl2: '(6) Warriors: All Warriors gain an additional 8 armor',
    heroClasslvl3: '(9) Warriors: All Warriors gain an additional 10 armor',
    heroClass1Icon: 'https://i.imgur.com/eat1oWG.png',
    ability1Icon: 'https://i.imgur.com/iVzkpCA.png',
    ability1Name: 'Berserkers Call',
    ability1Target: 'Target: Self',
    ability1Duration: 'Duration: 2/3/4',
    ability1Radius: 'Radius: 192',
    ability1Damage: 'Bonus Armor: 5/10/15',
    ability1Cooldown: 'Cooldown: 10',
    ability1Description: 'Axe taunts nearby enemy units, forcing them to attack him for the duration. Axe gains bonus armor during this effect.',
    ability2Icon: '',
    ability2Name: '',
    cost: '1',
    portrait: 'https://i.imgur.com/JH8VOhP.png',
    rank1: 'https://i.imgur.com/SSM0HRb.png',
    number: 4
  },
  {
    heroName: 'Bat Rider',
    race1: 'Troll',
    race1Icon: 'https://i.imgur.com/8Th2eZ9.png',
    race1Ability: 'Voodoo Frenzy',
    race1lvl1: '(2) Trolls: All Trolls gain 35 attack speed',
    race1lvl2: '(4) Trolls: All allies gain an additional 35 attack speed',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Knight',
    heroClass1Ability: 'Divine Protection',
    heroClasslvl1: '(2) Knights: 25% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClasslvl2: '(4) Knights: 35% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClasslvl3: '(6) Knights: 45% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClass1Icon: 'https://i.imgur.com/XTsv70x.png',
    ability1Icon: 'https://i.imgur.com/1rQI29j.png',
    ability1Name: 'Sticky Napalm',
    ability1Target: 'Target: AOE',
    ability1Duration: 'Duration: 20',
    ability1Radius: 'Radius: 375',
    ability1Damage: 'Damage: 50/75/100',
    ability1Cooldown: 'Cooldown: 3',
    ability1Description: "Drenches an area in sticky oil, amplifying damage from Batrider's attacks and slowing enemys movement by 3%/5%/7%.",
    ability2Icon: '',
    ability2Name: '',
    cost: '2',
    portrait: 'https://i.imgur.com/4PToigc.png',
    rank1: 'https://i.imgur.com/lOAHq7q.png',
    number: 5
  },
  {
    heroName: 'Beastmaster',
    race1: 'Orc',
    race1Icon: 'https://i.imgur.com/lrXutiw.png',
    race1Ability: 'Battle Hardened',
    race1lvl1: '(2) Orcs: All Orcs gain 250 max HP',
    race1lvl2: '(4) Orcs: All Orcs gain an additional 350 max hp',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Hunter',
    heroClass1Ability: 'Hunters Pack',
    heroClasslvl1: '(3) Hunters: All Hunters deal 25% more attack damage',
    heroClasslvl2: '(6) Hunters: All Hunters deal an additional 35% more attack damage',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/oD6geML.png',
    ability1Icon: 'https://i.imgur.com/MmDfxzT.png',
    ability1Name: 'Wild Axes',
    ability1DmgType: 'Type: Physical',
    ability1Target: 'Target: Enemy Units',
    ability1Duration: 'Duration: 7 seconds',
    ability1Radius: 'Range: 1500',
    ability1Damage: 'Damage: 60/100/140 per axe',
    ability1Cooldown: 'Cooldown: 7',
    ability1Description: 'Beastmaster sends his axes flying and calls them home again, slicing through enemy units and trees along their path. Each axe can hit an enemy once, and amplifies susequent damage from Beastmaster by 10/20/30.',
    ability2Icon: '',
    ability2Name: '',
    cost: '2',
    portrait: 'https://i.imgur.com/oJTLtzk.png',
    rank1: 'https://i.imgur.com/Lb4ZtSa.png',
    number: 6
  },
  {
    heroName: 'Bounty Hunter',
    race1: 'Goblin',
    race1Icon: 'https://i.imgur.com/e2CyWql.png',
    race1Ability: 'Nanobots',
    race1lvl1: '(3) Goblins: Increase Armor and HP Regen by 15 for a random ally',
    race1lvl2: '(6) Goblins: Increase Armor and HP Regen by 15 for all Goblins',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Assassin',
    heroClass1Ability: 'Coup de Grace',
    heroClasslvl1: '(3) Assassins: All Assassins gain a 10% chance to deal a 350% damage critical strike',
    heroClasslvl2: '(6) Assassins: All Assassins gain an additional 20% chance to deal a 350% damage critical strike',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/0r0Ivea.png',
    ability1Icon: 'https://i.imgur.com/mIFFz2I.png',
    ability1Name: 'Shuriken Toss',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: Enemy Units',
    ability1Damage: 'Damage: 300/500/700',
    ability1Cooldown: 'Cooldown: 5',
    ability1Description: 'Bounty Hunter hurls a deadly shuriken at an enemy unit, dealing damage and stunning the target.',
    ability2Icon: '',
    ability2Name: '',
    cost: '2',
    portrait: 'https://i.imgur.com/0jDQwHd.png',
    rank1: 'https://i.imgur.com/kqqLgVI.png',
    number: 7
  },
  {
    heroName: 'Chaos Knight',
    race1: 'Demon',
    race1Icon: 'https://i.imgur.com/oSLSl5s.png',
    race1Ability: 'Fel Power',
    race1lvl1: 'Unique: If this unit is the only Demon on your battlefield, it deal an addition 50% pure damage',
    race1lvl2: '',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Knight',
    heroClass1Ability: 'Divine Protection',
    heroClasslvl1: '(2) Knights: 25% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClasslvl2: '(4) Knights: 35% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClasslvl3: '(6) Knights: 45% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClass1Icon: 'https://i.imgur.com/XTsv70x.png',
    ability1Icon: 'https://i.imgur.com/Y7HqyEk.png',
    ability1Name: 'Chaos Bolt',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: Enemy Units',
    ability1Damage: 'Damage: 50/100/150-200/300/400',
    ability1Cooldown: 'Cooldown: 5',
    ability1Description: 'Throws a mysterious bolt of energy at the target unit. It stuns for a random duration of 1-4 seconds and deals random damage.',
    ability2Icon: '',
    ability2Name: '',
    cost: '2',
    portrait: 'https://i.imgur.com/6IULKu3.png',
    rank1: 'https://i.imgur.com/DVEXtqJ.png',
    number: 8
  },
  {
    heroName: 'Clockwerk',
    race1: 'Goblin',
    race1Icon: 'https://i.imgur.com/e2CyWql.png',
    race1Ability: 'Nanobots',
    race1lvl1: '(3) Goblins: Increase Armor and HP Regen by 15 for a random ally',
    race1lvl2: '(6) Goblins: Increase Armor and HP Regen by 15 for all Goblins',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Mech',
    heroClass1Ability: 'Self Repair',
    heroClasslvl1: '(2) Mechs: All Mechs gain 10 HP regeneration',
    heroClasslvl2: '(4) Mechs: All Mechs gain an additional 20 HP regeneration',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/SSphR17.png',
    ability1Icon: 'https://i.imgur.com/CTAUlc4.png',
    ability1Name: 'Battery Assault',
    ability1DmgType: 'Type: Magical',
    ability1Duration: 'Duration: 5 seconds',
    ability1Radius: 'Radius: 275',
    ability1Damage: 'Damage: 50/75/100',
    ability1Cooldown: 'Cooldown: 12/10/8',
    ability1Description: 'Discharges high-powered shrapnel every .7 seconds at randoms nearby enemies, dealing minor magical damage and inflicting stun.',
    ability2Icon: '',
    ability2Name: '',
    cost: '1',
    portrait: 'https://i.imgur.com/PwiVlz9.png',
    rank1: 'https://i.imgur.com/HJ2oJ9K.png',
    number: 9
  },
  {
    heroName: 'Crystal Maiden',
    race1: 'Human',
    race1Icon: 'https://i.imgur.com/ttRRwrJ.png',
    race1Ability: 'Persuasion',
    race1lvl1: '(2) Humans: All Humans have a 20% chance to disarm an enemy unit on attacks',
    race1lvl2: '(4) Humans: All Humans have an additional 25% chance to disarm an enemy unit on attack',
    race1lvl3: '(6) Humans: All Humans have an additional 35% chance to disarm an enemy unit on attack',
    race2: '',
    race2Icon: '',
    heroClass1: 'Mage',
    heroClass1Ability: 'Magic Vulnerability',
    heroClasslvl1: '(3) Mages: All enemies lose 40 magic resist',
    heroClasslvl2: '(6) Mages: All enemies lose an additional 40 magic resist',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/XDFw9NC.png',
    ability1Icon: 'https://i.imgur.com/XDFw9NC.png',
    ability1Name: 'Arcane Aura',
    ability1Target: 'Target: Allied Units',
    ability1Duration: 'Duration: Aura',
    ability1Cooldown: 'Aura',
    ability1Description: 'All allies have 8/14/20 additional mana generation every 3 seconds.',
    ability2Icon: '',
    ability2Name: '',
    cost: '2',
    portrait: 'https://i.imgur.com/39LtVZW.png',
    rank1: 'https://i.imgur.com/pkaYS3s.png',
    number: 10
  },
  {
    heroName: 'Disruptor',
    race1: 'Orc',
    race1Icon: 'https://i.imgur.com/lrXutiw.png',
    race1Ability: 'Battle Hardened',
    race1lvl1: '(2) Orcs: All Orcs gain 250 max HP',
    race1lvl2: '(4) Orcs: All Orcs gain an additional 350 max hp',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Shaman',
    heroClass1Ability: 'Hex',
    heroClasslvl1: '(2) Shaman: Apply Hex to a random enemy unit at the start of each round',
    heroClasslvl2: '',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/YvPL46t.png',
    ability1Icon: 'https://i.imgur.com/f1FguTP.png',
    ability1Name: 'Static Storm',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: AOE',
    ability1Duration: 'Duration: 3',
    ability1Radius: 'Radius: 400/500/600',
    ability1Damage: 'Damage: 100/200/300 max per second',
    ability1Cooldown: 'Cooldown: 15/12/9',
    ability1Description: 'Creates a damaging static storm that also silences all enemy units in the area for the duration. The damage starts off weak but increases in power over the duration.',
    ability2Icon: 'https://i.imgur.com/OuAs7Lx.png',
    ability2Name: 'Hex',
    ability2Target: 'Target: Enemy Units',
    ability2Duration: 'Duration: 3',
    ability2Cooldown: 'Activates: Round Start',
    ability2Description: 'Transforms an enemy unit into a harmless frog, disabling all attacks and abilities for the duration of the effect.',
    cost: '4',
    portrait: 'https://i.imgur.com/Lfzq24Z.png',
    rank1: 'https://i.imgur.com/CyDmLnF.png',
    number: 11
  },
  {
    heroName: 'Doom',
    race1: 'Demon',
    race1Icon: 'https://i.imgur.com/oSLSl5s.png',
    race1Ability: 'Fel Power',
    race1lvl1: 'Unique: If this unit is the only Demon on your battlefield, it deal an addition 50% pure damage',
    race1lvl2: '',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Warrior',
    heroClass1Ability: 'Fortified Armor',
    heroClasslvl1: '(3) Warriors: All Warriors gain 7 armor',
    heroClasslvl2: '(6) Warriors: All Warriors gain an additional 8 armor',
    heroClasslvl3: '(9) Warriors: All Warriors gain an additional 10 armor',
    heroClass1Icon: 'https://i.imgur.com/eat1oWG.png',
    ability1Icon: 'https://i.imgur.com/LzCfl1E.png',
    ability1Name: 'Doom',
    ability1DmgType: 'Type: Pure',
    ability1Target: 'Target: Enemy Units',
    ability1Duration: 'Duration: 20',
    ability1Damage: 'Damage: 60/90/120 per second',
    ability1Cooldown: 'Cooldown: 10',
    ability1Description: 'Inflicts a curse that prevents an enemy from casting spells or using items, while taking damage over time.',
    ability2Icon: '',
    ability2Name: '',
    cost: '4',
    portrait: 'https://i.imgur.com/p4f7VrE.png',
    rank1: 'https://i.imgur.com/TotTLYN.jpg',
    number: 12
  },
  {
    heroName: 'Dragon Knight',
    race1: 'Human',
    race1Icon: 'https://i.imgur.com/ttRRwrJ.png',
    race1Ability: 'Persuasion',
    race1lvl1: '(2) Humans: All Humans have a 20% chance to disarm an enemy unit on attacks',
    race1lvl2: '(4) Humans: All Humans have an additional 25% chance to disarm an enemy unit on attack',
    race1lvl3: '(6) Humans: All Humans have an additional 35% chance to disarm an enemy unit on attack',
    race2: 'Dragon',
    race2Ability: 'Attunement',
    race2Icon: 'https://i.imgur.com/ayX9w4V.png',
    race2lvl1: '(3) Dragons: All Dragons start each round with 100 mana',
    heroClass1: 'Knight',
    heroClass1Ability: 'Divine Protection',
    heroClasslvl1: '(2) Knights: 25% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClasslvl2: '(4) Knights: 35% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClasslvl3: '(6) Knights: 45% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClass1Icon: 'https://i.imgur.com/XTsv70x.png',
    ability1Icon: 'https://i.imgur.com/iHC1QjB.png',
    ability1Name: 'Elder Dragon Form',
    ability1DmgType: 'Type: Transformation',
    ability1Duration: 'Duration: 60',
    ability1Damage: 'Damage: 100/150/200',
    ability1Cooldown: 'Cooldown: 60',
    ability1Description: 'Dragon Knight transforms into one of three powerful elder dragons, increasing his speed by 30, range by 350, and gaining new powers',
    ability2Icon: '',
    ability2Name: '',
    cost: '4',
    portrait: 'https://i.imgur.com/9x8yK0J.png',
    rank1: 'https://i.imgur.com/I2qD0nd.png',
    number: 13
  },
  {
    heroName: 'Drow Ranger',
    race1: 'Undead',
    race1Icon: 'https://i.imgur.com/jdIK8RD.png',
    race1Ability: 'Horror',
    race1lvl1: '(2) Undead: All enemies lose 6 armor',
    race1lvl2: '(4) Undead: All enemies lose an additional 8 armor',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Hunter',
    heroClass1Ability: 'Hunters Pack',
    heroClasslvl1: '(3) Hunters: All Hunters deal 25% more attack damage',
    heroClasslvl2: '(6) Hunters: All Hunters deal an additional 35% more attack damage',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/oD6geML.png',
    ability1Icon: 'https://i.imgur.com/kH6kBgA.png',
    ability1Name: 'Marksmanship',
    ability1Cooldown: 'Aura',
    ability1Description: 'Increases attack damage and attack speed by 20%/30%/40% for Drow Ranger.',
    ability2Icon: '',
    ability2Name: '',
    cost: '1',
    portrait: 'https://i.imgur.com/t80klYt.png',
    rank1: 'https://i.imgur.com/J5krXWw.png',
    number: 14
  },
  {
    heroName: 'Enchantress',
    race1: 'Beast',
    race1Icon: 'https://i.imgur.com/eHGjBh1.png',
    race1Ability: 'Power of the Wild',
    race1lvl1: '(2) Beasts: All allies gain 10% attack damage',
    race1lvl2: '(4) Beasts: All allies gain an additional 15% attack damage',
    race1lvl3: '(6) Beasts: All allies gain an additional 20% attack damage',
    race2: '',
    race2Icon: '',
    heroClass1: 'Druid',
    heroClass1Ability: 'Synergy',
    heroClasslvl1: '(2) Druids: Druids only require combining 2 chess pieces to reach level 2',
    heroClasslvl2: '(4) Druids: Druids only require combining 2 level 2 chess pieces to reach level 3',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/wC70fdy.png',
    ability1Icon: 'https://i.imgur.com/O2xDMQV.png',
    ability1Name: 'Natures Attendants',
    ability1Target: 'Target: Allied Units',
    ability1Duration: 'Duration: 11 Seconds',
    ability1Radius: 'Radius: 500',
    ability1Damage: 'Healing: 25 HP/second',
    ability1Cooldown: 'Cooldown: 15',
    ability1Description: 'A cloud of 3/5/7 wisps heals Enchantress and any friendly units nearby.',
    ability2Icon: '',
    ability2Name: '',
    cost: '1',
    portrait: 'https://i.imgur.com/0VBOF5I.png',
    rank1: 'https://i.imgur.com/ZtWuymX.png',
    number: 15
  },
  {
    heroName: 'Enigma',
    race1: 'Elemental',
    race1Icon: 'https://i.imgur.com/yfXfVL9.png',
    race1Ability: 'Elemental Resistance',
    race1lvl1: '(2) Elementals: Elementals have a 30% chance to turn melee attackers into stone for 3 seconds',
    race1lvl2: '(4) Elementals: Allies have a 30% chance to turn melee attackers into stone for 3 seconds',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Warlock',
    heroClass1Ability: 'Life Steal',
    heroClasslvl1: '(3) Warlocks: All allies gain 15% lifesteal',
    heroClasslvl2: '(6) Warlocks: All allies gain an additional 25% lifesteal',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/OngJXn3.png',
    ability1Icon: 'https://i.imgur.com/ACzJoBi.png',
    ability1Name: 'Midnight Pulse',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: AOE',
    ability1Duration: 'Duration: 10',
    ability1Radius: 'Radius: 450',
    ability1Damage: 'Damage: 5%/7%/9% Max HP',
    ability1Cooldown: 'Cooldown: 20',
    ability1Description: 'Steeps an area in dark resonance, damaging enemies based on their max HP.',
    ability2Icon: '',
    ability2Name: '',
    cost: '5',
    portrait: 'https://i.imgur.com/91afsPO.png',
    rank1: 'https://i.imgur.com/k1aNENj.png',
    number: 16
  },
  {
    heroName: 'Furion',
    race1: 'Elf',
    race1Icon: 'https://i.imgur.com/Wy9ES4n.png',
    race1Ability: 'Persuasion',
    race1lvl1: '(3) Elves: All Elves gain 25% evasion from enemy attacks',
    race1lvl2: '(6) Elves: All Elves gain an additional 25% evasion from enemy attacks',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Druid',
    heroClass1Ability: 'Synergy',
    heroClasslvl1: '(2) Druids: Druids only require combining 2 chess pieces to reach level 2',
    heroClasslvl2: '(4) Druids: Druids only require combining 2 level 2 chess pieces to reach level 3',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/wC70fdy.png',
    ability1Icon: 'https://i.imgur.com/VsgWFxr.png',
    ability1Name: 'Natures Call',
    ability1DmgType: 'Type: Summon',
    ability1Duration: 'Duration: 60',
    ability1Cooldown: 'Cooldown: 7',
    ability1Description: 'Calls a treant from a random tree around the chessboard that damages enemies.',
    ability2Icon: '',
    ability2Name: '',
    cost: '2',
    portrait: 'https://i.imgur.com/keHl3rP.png',
    rank1: 'https://i.imgur.com/CWJrsoT.png',
    number: 17
  },
  {
    heroName: 'Gyrocopter',
    race1: 'Dwarf',
    race1Icon: 'https://i.imgur.com/J6LcqKh.png',
    race1Ability: 'Take Aim',
    race1lvl1: ' (1) Dwarf: This unit gains 300 attack range',
    race1lvl2: '',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Mech',
    heroClass1Ability: 'Self Repair',
    heroClasslvl1: '(2) Mechs: All Mechs gain 10 HP regeneration',
    heroClasslvl2: '(4) Mechs: All Mechs gain an additional 20 HP regeneration',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/SSphR17.png',
    ability1Icon: 'https://i.imgur.com/xNQNeW6.png',
    ability1Name: 'Call Down',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: AOE',
    ability1Duration: 'Duration: 6',
    ability1Radius: 'Radius: 600',
    ability1Damage: 'Damage: 200/300/400 per missile',
    ability1Cooldown: 'Cooldown: 10',
    ability1Description: 'Calls down an aerial missile strike on enemies in a target area. Two missiles arrive in succession, the first dealing damage and a 30% slow for 2 seconds, the second dealing damage and a 60% slow for 4 seconds',
    ability2Icon: '',
    ability2Name: '',
    cost: '5',
    portrait: 'https://i.imgur.com/wuTmVmq.png',
    rank1: 'https://i.imgur.com/1IhPzr6.png',
    number: 18
  },
  {
    heroName: 'Juggernaut',
    race1: 'Orc',
    race1Icon: 'https://i.imgur.com/lrXutiw.png',
    race1Ability: 'Battle Hardened',
    race1lvl1: '(2) Orcs: All Orcs gain 250 max HP',
    race1lvl2: '(4) Orcs: All Orcs gain an additional 350 max hp',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Warrior',
    heroClass1Ability: 'Fortified Armor',
    heroClasslvl1: '(3) Warriors: All Warriors gain 7 armor',
    heroClasslvl2: '(6) Warriors: All Warriors gain an additional 8 armor',
    heroClasslvl3: '(9) Warriors: All Warriors gain an additional 10 armor',
    heroClass1Icon: 'https://i.imgur.com/eat1oWG.png',
    ability1Icon: 'https://i.imgur.com/wzyeinP.png',
    ability1Name: 'Blade Fury',
    ability1DmgType: 'Type: Magical',
    ability1Duration: 'Duration: 5 seconds',
    ability1Radius: 'Radius: 250',
    ability1Damage: 'Damage: 50/100/150',
    ability1Cooldown: 'Cooldown: 12',
    ability1Description: 'Causes a bladestorm of destructive force around Juggernaut, dealing damage to all nearby units and making Juggernaut immune to all magic damage and effects.',
    ability2Icon: '',
    ability2Name: '',
    cost: '2',
    portrait: 'https://i.imgur.com/ho3CyQR.png',
    rank1: 'https://i.imgur.com/FZsCFMA.png',
    number: 19
  },
  {
    heroName: 'Keeper of the Light',
    race1: 'Human',
    race1Icon: 'https://i.imgur.com/ttRRwrJ.png',
    race1Ability: 'Persuasion',
    race1lvl1: '(2) Humans: All Humans have a 20% chance to disarm an enemy unit on attacks',
    race1lvl2: '(4) Humans: All Humans have an additional 25% chance to disarm an enemy unit on attack',
    race1lvl3: '(6) Humans: All Humans have an additional 35% chance to disarm an enemy unit on attack',
    race2: '',
    race2Icon: '',
    heroClass1: 'Mage',
    heroClass1Ability: 'Magic Vulnerability',
    heroClasslvl1: '(3) Mages: All enemies lose 40 magic resist',
    heroClasslvl2: '(6) Mages: All enemies lose an additional 40 magic resist',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/XDFw9NC.png',
    ability1Icon: 'https://i.imgur.com/FCxK0Xp.png',
    ability1Name: 'Illuminate',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: Enemy Units',
    ability1Radius: 'Range: 1000',
    ability1Damage: 'Damage: 300/450/600',
    ability1Cooldown: 'Cooldown: 10/8/6',
    ability1Description: 'Channels light energy for a maximum of 3 seconds, building power the longer it is channeled. Once released, a wave is sent forth that deals damage to all enemies in its path, growing wider the further it travels to a maxmimum width of 300.',
    ability2Icon: '',
    ability2Name: '',
    cost: '4',
    portrait: 'https://i.imgur.com/UCIPtkg.png',
    rank1: 'https://i.imgur.com/NcQfisb.png',
    number: 20
  },
  {
    heroName: 'Kunkka',
    race1: 'Human',
    race1Icon: 'https://i.imgur.com/ttRRwrJ.png',
    race1Ability: 'Persuasion',
    race1lvl1: '(2) Humans: All Humans have a 20% chance to disarm an enemy unit on attacks',
    race1lvl2: '(4) Humans: All Humans have an additional 25% chance to disarm an enemy unit on attack',
    race1lvl3: '(6) Humans: All Humans have an additional 35% chance to disarm an enemy unit on attack',
    race2: '',
    race2Icon: '',
    heroClass1: 'Warrior',
    heroClass1Ability: 'Fortified Armor',
    heroClasslvl1: '(3) Warriors: All Warriors gain 7 armor',
    heroClasslvl2: '(6) Warriors: All Warriors gain an additional 8 armor',
    heroClasslvl3: '(9) Warriors: All Warriors gain an additional 10 armor',
    heroClass1Icon: 'https://i.imgur.com/eat1oWG.png',
    ability1Icon: 'https://i.imgur.com/h1zbMkm.png',
    ability1Name: 'Ghost Ship',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: AOE',
    ability1Duration: 'Duration: 1.4/1.7/2 Seconds',
    ability1Radius: 'Radius: 425',
    ability1Damage: 'Damage: 150/250/350',
    ability1Cooldown: 'Cooldown: 10',
    ability1Description: 'Summons a ghostly ship that sails through the battle before smashing apart, damaging and stunning all enemies caught near the wreckage.',
    ability2Icon: '',
    ability2Name: '',
    cost: '4',
    portrait: 'https://i.imgur.com/C9xLBHS.png',
    rank1: 'https://i.imgur.com/VnQaQYk.png',
    number: 21
  },
  {
    heroName: 'Lich',
    race1: 'Undead',
    race1Icon: 'https://i.imgur.com/jdIK8RD.png',
    race1Ability: 'Horror',
    race1lvl1: '(2) Undead: All enemies lose 6 armor',
    race1lvl2: '(4) Undead: All enemies lose an additional 8 armor',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Mage',
    heroClass1Ability: 'Magic Vulnerability',
    heroClasslvl1: '(3) Mages: All enemies lose 40 magic resist',
    heroClasslvl2: '(6) Mages: All enemies lose an additional 40 magic resist',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/XDFw9NC.png',
    ability1Icon: 'https://i.imgur.com/UWPQD6M.png',
    ability1Name: 'Chain Frost',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: Enemy Units',
    ability1Duration: 'Duration: 6/9/12 Bounces',
    ability1Radius: 'Radius: 600',
    ability1Damage: 'Damage: 200/300/400 Per Bounce',
    ability1Cooldown: 'Cooldown: 10/8/6',
    ability1Description: 'Release an orb of frost that bounces between nearby enemies up to 6/9/12 times, slowing their movement and attack speed 65% for 2.5 seconds and damaging them.',
    ability2Icon: '',
    ability2Name: '',
    cost: '5',
    portrait: 'https://i.imgur.com/TdXnv66.png',
    rank1: 'https://i.imgur.com/gwmOjBQ.png',
    number: 22
  },
  {
    heroName: 'Lina',
    race1: 'Human',
    race1Icon: 'https://i.imgur.com/ttRRwrJ.png',
    race1Ability: 'Persuasion',
    race1lvl1: '(2) Humans: All Humans have a 20% chance to disarm an enemy unit on attacks',
    race1lvl2: '(4) Humans: All Humans have an additional 25% chance to disarm an enemy unit on attack',
    race1lvl3: '(6) Humans: All Humans have an additional 35% chance to disarm an enemy unit on attack',
    race2: '',
    race2Icon: '',
    heroClass1: 'Mage',
    heroClass1Ability: 'Magic Vulnerability',
    heroClasslvl1: '(3) Mages: All enemies lose 40 magic resist',
    heroClasslvl2: '(6) Mages: All enemies lose an additional 40 magic resist',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/XDFw9NC.png',
    ability1Icon: 'https://i.imgur.com/12ucWOd.png',
    ability1Name: 'Laguna Blade',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: Enemy Units',
    ability1Damage: 'Damage: 500/750/1000',
    ability1Cooldown: 'Cooldown: 13/10/7',
    ability1Description: 'Fires off a bolt of lightning at a single enemy unit, dealing massive damage.',
    ability2Icon: '',
    ability2Name: '',
    cost: '3',
    portrait: 'https://i.imgur.com/8QIjXwo.png',
    rank1: 'https://i.imgur.com/jOzcjZP.png',
    number: 23
  },
  {
    heroName: 'Lone Druid',
    race1: 'Beast',
    race1Icon: 'https://i.imgur.com/eHGjBh1.png',
    race1Ability: 'Power of the Wild',
    race1lvl1: '(2) Beasts: All allies gain 10% attack damage',
    race1lvl2: '(4) Beasts: All allies gain an additional 15% attack damage',
    race1lvl3: '(6) Beasts: All allies gain an additional 20% attack damage',
    race2: '',
    race2Icon: '',
    heroClass1: 'Druid',
    heroClass1Ability: 'Synergy',
    heroClasslvl1: '(2) Druids: Druids only require combining 2 chess pieces to reach level 2',
    heroClasslvl2: '(4) Druids: Druids only require combining 2 level 2 chess pieces to reach level 3',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/wC70fdy.png',
    ability1Icon: 'https://i.imgur.com/edHUewJ.png',
    ability1Name: 'Spirit Bear',
    ability1DmgType: 'Type: Summon',
    ability1Duration: 'Duration: 60',
    ability1Cooldown: 'Cooldown: 60',
    ability1Description: 'Summons a powerful spirit bear that will function as its own unit.',
    ability2Icon: '',
    ability2Name: '',
    cost: '4',
    portrait: 'https://i.imgur.com/5koYzH4.png',
    rank1: 'https://i.imgur.com/hzhsyoE.png',
    number: 24
  },
  {
    heroName: 'Luna',
    race1: 'Elf',
    race1Icon: 'https://i.imgur.com/Wy9ES4n.png',
    race1Ability: 'Evasion',
    race1lvl1: '(3) Elves: All Elves gain 25% evasion from enemy attacks',
    race1lvl2: '(6) Elves: All Elves gain an additional 25% evasion from enemy attacks',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Knight',
    heroClass1Ability: 'Divine Protection',
    heroClasslvl1: '(2) Knights: 25% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClasslvl2: '(4) Knights: 35% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClasslvl3: '(6) Knights: 45% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClass1Icon: 'https://i.imgur.com/XTsv70x.png',
    ability1Icon: 'https://i.imgur.com/9hoH1YV.png',
    ability1Name: 'Moon Glaives',
    ability1DmgType: 'Type: Physical',
    ability1Target: 'Target: Enemy Units',
    ability1Radius: 'Radius: 500',
    ability1Damage: 'Damage: 30% Reduction Per Bounce',
    ability1Cooldown: "Cooldown: Luna's glaives are empowered, causing her attacks to bounce between 3/5/7 enemy units. Deals less damage with each bounce.",
    ability1Description: '',
    ability2Icon: '',
    ability2Name: '',
    cost: '2',
    portrait: 'https://i.imgur.com/UDiw1PH.png',
    rank1: 'https://i.imgur.com/CPCPhiK.png',
    number: 25
  },
  {
    heroName: 'Lycan',
    race1: 'Human',
    race1Icon: 'https://i.imgur.com/ttRRwrJ.png',
    race1Ability: 'Persuasion',
    race1lvl1: '(2) Humans: All Humans have a 20% chance to disarm an enemy unit on attacks',
    race1lvl2: '(4) Humans: All Humans have an additional 25% chance to disarm an enemy unit on attack',
    race1lvl3: '(6) Humans: All Humans have an additional 35% chance to disarm an enemy unit on attack',
    race2: 'Beast',
    race2Icon: 'https://i.imgur.com/eHGjBh1.png',
    race2Ability: 'Power of the Wild',
    race2lvl1: '(2) Beasts: All allies gain 10% attack damage',
    race2lvl2: '(4) Beasts: All allies gain an additional 15% attack damage',
    race2lvl3: '(6) Beasts: All allies gain an additional 20% attack damage',
    heroClass1: 'Warrior',
    heroClass1Ability: 'Fortified Armor',
    heroClasslvl1: '(3) Warriors: All Warriors gain 7 armor',
    heroClasslvl2: '(6) Warriors: All Warriors gain an additional 8 armor',
    heroClasslvl3: '(9) Warriors: All Warriors gain an additional 10 armor',
    heroClass1Icon: 'https://i.imgur.com/eat1oWG.png',
    ability1Icon: 'https://i.imgur.com/5UJc9RK.png',
    ability1Name: 'Transform',
    ability1DmgType: 'Type: Transformation',
    ability1Target: 'Target: Self',
    ability1Duration: 'Duration: 60',
    ability1Cooldown: 'Cooldown: 60',
    ability1Description: 'Lycan assumes his Lupine form, gaining an additional 20%/30%/40% HP and summoning two wolves.',
    ability2Icon: '',
    ability2Name: '',
    cost: '3',
    portrait: 'https://i.imgur.com/gsdho2W.png',
    rank1: 'https://i.imgur.com/32Aj6oz.png',
    number: 26
  },
  {
    heroName: 'Medusa',
    race1: 'Naga',
    race1Icon: 'https://i.imgur.com/lO6z92w.png',
    race1Ability: 'Scale Armor',
    race1lvl1: '(2) Naga: All allies gain 20 magic resist',
    race1lvl2: '(4) Naga: All allies gain an additional 40 magic resist',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Hunter',
    heroClass1Ability: 'Hunters Pack',
    heroClasslvl1: '(3) Hunters: All Hunters deal 25% more attack damage',
    heroClasslvl2: '(6) Hunters: All Hunters deal an additional 35% more attack damage',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/oD6geML.png',
    ability1Icon: 'https://i.imgur.com/yNhoAyv.png',
    ability1Name: 'Stone Gaze',
    ability1DmgType: 'Type: Physical',
    ability1Target: 'Target: AOE',
    ability1Duration: 'Duration: 4/5/6',
    ability1Radius: 'Radius: 600/800/1000',
    ability1Damage: 'Damage: 30% Bonus',
    ability1Cooldown: 'Cooldown: 20',
    ability1Description: 'Any enemies looking at Medusa have their attack speed and movement slowed. If 2 seconds of total time is accumulated looking at Medusa while Stone Gaze is active, that unit will turn to stone for 2/3/4 seconds. Petrified units are stunned and take bonus physical damage.',
    ability2Icon: '',
    ability2Name: '',
    cost: '4',
    portrait: 'https://i.imgur.com/Hfdrt3z.png',
    rank1: 'https://i.imgur.com/l5d9OOi.png',
    number: 27
  },
  {
    heroName: 'Morphling',
    race1: 'Elemental',
    race1Icon: 'https://i.imgur.com/yfXfVL9.png',
    race1Ability: 'Elemental Resistance',
    race1lvl1: '(2) Elementals: Elementals have a 30% chance to turn melee attackers into stone for 3 seconds',
    race1lvl2: '(4) Elementals: Allies have a 30% chance to turn melee attackers into stone for 3 seconds',
    heroClass1: 'Assassin',
    heroClass1Ability: 'Coup de Grace',
    heroClasslvl1: '(3) Assassins: All Assassins gain a 10% chance to deal a 350% damage critical strike',
    heroClasslvl2: '(6) Assassins: All Assassins gain an additional 20% chance to deal a 350% damage critical strike',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/0r0Ivea.png',
    ability1Icon: 'https://i.imgur.com/ya3lbBX.png',
    ability1Name: 'Waveform',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: AOE',
    ability1Radius: 'Range: 1000',
    ability1Damage: 'Damage: 150/250/350',
    ability1Cooldown: 'Cooldown: 10/8/6',
    ability1Description: 'Morphling dissolves into liquid and surges forward, damaging enemy units in his path. Morphling is invulnerable during Waveform.',
    ability2Icon: '',
    ability2Name: '',
    cost: '2',
    portrait: 'https://i.imgur.com/h8N1zF9.png',
    rank1: 'https://i.imgur.com/skyq0IA.jpg',
    number: 28
  },
  {
    heroName: 'Necrophos',
    race1: 'Undead',
    race1Icon: 'https://i.imgur.com/jdIK8RD.png',
    race1Ability: 'Horror',
    race1lvl1: '(2) Undead: All enemies lose 6 armor',
    race1lvl2: '(4) Undead: All enemies lose an additional 8 armor',
    heroClass1: 'Warlock',
    heroClass1Ability: 'Life Steal',
    heroClasslvl1: '(3) Warlocks: All allies gain 15% lifesteal',
    heroClasslvl2: '(6) Warlocks: All allies gain an additional 25% lifesteal',
    heroClass1Icon: 'https://i.imgur.com/OngJXn3.png',
    ability1Icon: 'https://i.imgur.com/dVJdaln.png',
    ability1Name: 'Death Pulse',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: All Units',
    ability1Radius: 'Radius: 475',
    ability1Damage: 'Damage: 100/150/200 \xa0\xa0\xa0\xa0\xa0 Healing: 100/175/250',
    ability1Cooldown: 'Cooldown: 5',
    ability1Description: 'Necorophos releases a wave of death around him, dealing damage to enemies and healing allies.',
    ability2Icon: '',
    ability2Name: '',
    cost: '4',
    portrait: 'https://i.imgur.com/BtNkMWS.png',
    rank1: 'https://i.imgur.com/XTG57n3.png',
    number: 29
  },
  {
    heroName: 'Ogre Magi',
    race1: 'Ogre',
    race1Icon: 'https://i.imgur.com/sZjYBXJ.png',
    race1Ability: 'Two Heads',
    race1lvl1: '(1) Ogre: This unit gains 10% max HP',
    race1lvl2: '',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Mage',
    heroClass1Ability: 'Magic Vulnerability',
    heroClasslvl1: '(3) Mages: All enemies lose 40 magic resist',
    heroClasslvl2: '(6) Mages: All enemies lose an additional 40 magic resist',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/XDFw9NC.png',
    ability1Icon: 'https://i.imgur.com/ZoV8dEl.png',
    ability1Name: 'Bloodlust',
    ability1Target: 'Target: Allied Units',
    ability1Duration: 'Duration: 30',
    ability1Cooldown: 'Cooldown: 5',
    ability1Description: 'Incites a frenzy in a random ally, increase its movement speed by 8%/10%/12% and gaining 30/40/50 attack speed. If selfcast Ogre Magi gains 30/50/70 attack speed instead.',
    ability2Icon: '',
    ability2Name: '',
    cost: '1',
    portrait: 'https://i.imgur.com/TtiZx5c.png',
    rank1: 'https://i.imgur.com/sIfAjPZ.png',
    number: 30
  },
  {
    heroName: 'Omni Knight',
    race1: 'Human',
    race1Icon: 'https://i.imgur.com/ttRRwrJ.png',
    race1Ability: 'Persuasion',
    race1lvl1: '(2) Humans: All Humans have a 20% chance to disarm an enemy unit on attacks',
    race1lvl2: '(4) Humans: All Humans have an additional 25% chance to disarm an enemy unit on attack',
    race1lvl3: '(6) Humans: All Humans have an additional 35% chance to disarm an enemy unit on attack',
    race2: '',
    race2Icon: '',
    heroClass1: 'Knight',
    heroClass1Ability: 'Divine Protection',
    heroClasslvl1: '(2) Knights: 25% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClasslvl2: '(4) Knights: 35% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClasslvl3: '(6) Knights: 45% chance to gain a shield that grants 30 armor and 75% magic resistance for 3 seconds. Refreshes every 3 seconds.',
    heroClass1Icon: 'https://i.imgur.com/XTsv70x.png',
    ability1Icon: 'https://i.imgur.com/rJacfvH.png',
    ability1Name: 'Purification',
    ability1DmgType: 'Type: Pure',
    ability1Target: 'Target: Allied Units',
    ability1Radius: 'Radius: 260',
    ability1Damage: 'Damage/Healing: 200/300/400 ',
    ability1Cooldown: 'Cooldown: 10',
    ability1Description: 'Instantly heals a friendly unit and damages all nearby units for the same amount.',
    ability2Icon: '',
    ability2Name: '',
    cost: '3',
    portrait: 'https://i.imgur.com/pQtKwdD.png',
    rank1: 'https://i.imgur.com/DWYsMlt.png',
    number: 31
  },
  {
    heroName: 'Phantom Assassin',
    race1: 'Elf',
    race1Icon: 'https://i.imgur.com/Wy9ES4n.png',
    race1Ability: 'Evasion',
    race1lvl1: '(3) Elves: All Elves gain 25% evasion from incoming attacks',
    race1lvl2: '(6) Elves: All Elves gain an additional 25% evasions from incoming attacks',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Assassin',
    heroClass1Ability: 'Coup de Grace',
    heroClasslvl1: '(3) Assassins: All Assassins gain a 10% chance to deal a 350% damage critical strike',
    heroClasslvl2: '(6) Assassins: All Assassins gain an additional 20% chance to deal a 350% damage critical strike',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/0r0Ivea.png',
    ability1Icon: 'https://i.imgur.com/QgXZ1UU.png',
    ability1Name: 'Coup de Grace',
    ability1DmgType: 'Type: Physical',
    ability1Damage: 'Damage: 300%/450%/600%',
    ability1Cooldown: 'Aura',
    ability1Description: 'Phantom Assassin refines her combat ablities, gaining a 10% chance of delivering a devastating critical strike to enemy units.',
    ability2Icon: '',
    ability2Name: '',
    cost: '3',
    portrait: 'https://i.imgur.com/otTuibl.png',
    rank1: 'https://i.imgur.com/eSWoLbV.png',
    number: 32
  },
  {
    heroName: 'Puck',
    race1: 'Elf',
    race1Icon: 'https://i.imgur.com/Wy9ES4n.png',
    race1Ability: 'Evasion',
    race1lvl1: '(3) Elves: All Elves gain 25% evasion from incoming attacks',
    race1lvl2: '(6) Elves: All Elves gain an additional 25% evasions from incoming attacks',
    race1lvl3: '',
    race2: 'Dragon',
    race2Icon: 'https://i.imgur.com/ayX9w4V.png',
    race2Ability: 'Attunement',
    race2lvl1: '(3) Dragons: All Dragons start each round with 100 mana',
    heroClass1: 'Mage',
    heroClass1Ability: 'Magic Vulnerability',
    heroClasslvl1: '(3) Mages: All enemies lose 40 magic resist',
    heroClasslvl2: '(6) Mages: All enemies lose an additional 40 magic resist',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/XDFw9NC.png',
    ability1Icon: 'https://i.imgur.com/y4EjWz9.png',
    ability1Name: 'Illusory Orb',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: AOE',
    ability1Radius: 'Range: 800',
    ability1Damage: 'Damage: 150/200/250',
    ability1Cooldown: 'Cooldown: 5/4/3',
    ability1Description: 'Puck launches a magic orb that floats in a straight path, damaging enemy units along the way.',
    ability2Icon: '',
    ability2Name: '',
    cost: '2',
    portrait: 'https://i.imgur.com/DppMbXA.png',
    rank1: 'https://i.imgur.com/WQiMa5I.png',
    number: 33
  },
  {
    heroName: 'Queen of Pain',
    race1: 'Demon',
    race1Icon: 'https://i.imgur.com/oSLSl5s.png',
    race1Ability: 'Fel Power',
    race1lvl1: 'Unique: If this unit is the only Demon on your battlefield, it deal an addition 50% pure damage',
    race1lvl2: '',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Assassin',
    heroClass1Ability: 'Coup de Grace',
    heroClasslvl1: '(3) Assassins: All Assassins gain a 10% chance to deal a 350% damage critical strike',
    heroClasslvl2: '(6) Assassins: All Assassins gain an additional 20% chance to deal a 350% damage critical strike',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/0r0Ivea.png',
    ability1Icon: 'https://i.imgur.com/sTvOfrF.png',
    ability1Name: 'Scream of Pain',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: AOE',
    ability1Radius: 'Radius: 425',
    ability1Damage: 'Damage: 200/300/400',
    ability1Cooldown: 'Cooldown: 6',
    ability1Description: 'The Queen of Pain lets loose a piercing scream around her, damaging nearby enemies.',
    ability2Icon: '',
    ability2Name: '',
    cost: '2',
    portrait: 'https://i.imgur.com/wNwhkZ2.png',
    rank1: 'https://i.imgur.com/eARINj1.png',
    number: 34
  },
  {
    heroName: 'Razor',
    race1: 'Elemental',
    race1Icon: 'https://i.imgur.com/yfXfVL9.png',
    race1Ability: 'Elemental Resistance',
    race1lvl1: '(2) Elementals: Elementals have a 30% chance to turn melee attackers into stone for 3 seconds',
    race1lvl2: '(4) Elementals: Allies have a 30% chance to turn melee attackers into stone for 3 seconds',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Mage',
    heroClass1Ability: 'Magic Vulnerability',
    heroClasslvl1: '(3) Mages: All enemies lose 40 magic resist',
    heroClasslvl2: '(6) Mages: All enemies lose an additional 40 magic resist',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/XDFw9NC.png',
    ability1Icon: 'https://i.imgur.com/Ud0cZiU.png',
    ability1Name: 'Plasma Field',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: AOE',
    ability1Duration: 'Duration: 1.5',
    ability1Radius: 'Radius: 400/500/600',
    ability1Damage: 'Damage: 10-100/175/250',
    ability1Cooldown: 'Cooldown: 10',
    ability1Description: 'Releases a wave of energetic plasma that grows in power as it expands, but also zaps on contraction, slowing and dealing damage to enemy units caught in its path. Damage and slow increases with distance from Razor. Plasma Field hits each enemy twice, once each direction.',
    ability2Icon: '',
    ability2Name: '',
    cost: '3',
    portrait: 'https://i.imgur.com/uyE9KN5.png',
    rank1: 'https://i.imgur.com/QgFgaZS.png',
    number: 35
  },
  {
    heroName: 'Sand King',
    race1: 'Beast',
    race1Icon: 'https://i.imgur.com/eHGjBh1.png',
    race1Ability: 'Power of the Wild',
    race1lvl1: '(2) Beasts: All allies gain 10% attack damage',
    race1lvl2: '(4) Beasts: All allies gain an additional 15% attack damage',
    race1lvl3: '(6) Beasts: All allies gain an additional 20% attack damage',
    race2: '',
    race2Icon: '',
    heroClass1: 'Assassin',
    heroClass1Ability: 'Coup de Grace',
    heroClasslvl1: '(3) Assassins: All Assassins gain a 10% chance to deal a 350% damage critical strike',
    heroClasslvl2: '(6) Assassins: All Assassins gain an additional 20% chance to deal a 350% damage critical strike',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/0r0Ivea.png',
    ability1Icon: 'https://i.imgur.com/Soor9lp.png',
    ability1Name: 'Burrowstrike',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: Enemy Units',
    ability1Duration: 'Duration: 2 ',
    ability1Damage: 'Damage: 150/250/350',
    ability1Cooldown: 'Cooldown: 12/10/8',
    ability1Description: 'Sand King burrows into the ground and tunnels forward, damaging and stunning enemy units above him for 2 seconds as he resurfaces.',
    ability2Icon: '',
    ability2Name: '',
    cost: '3',
    portrait: 'https://i.imgur.com/am8BHgu.png',
    rank1: 'https://i.imgur.com/O9k0MEq.png',
    number: 36
  },
  {
    heroName: 'Shadow Fiend',
    race1: 'Demon',
    race1Icon: 'https://i.imgur.com/oSLSl5s.png',
    race1Ability: 'Fel Power',
    race1lvl1: 'Unique: If this unit is the only Demon on your battlefield, it deal an addition 50% pure damage',
    race1lvl2: '',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Warlock',
    heroClass1Ability: 'Life Steal',
    heroClasslvl1: '(3) Warlocks: All allies gain 15% lifesteal',
    heroClasslvl2: '(6) Warlocks: All allies gain an additional 25% lifesteal',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/OngJXn3.png',
    ability1Icon: 'https://i.imgur.com/xjWjrwo.png',
    ability1Name: 'Requiem of Souls',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: AOE',
    ability1Radius: 'Radius: 800',
    ability1Damage: 'Damage: 100/150/200',
    ability1Cooldown: 'Cooldown: 20',
    ability1Description: 'Shadow Fiend gathers his captured souls to release them as lines of demonic energy, damaging any enemy units hit.',
    ability2Icon: '',
    ability2Name: '',
    cost: '3',
    portrait: 'https://i.imgur.com/aqciBOn.png',
    rank1: 'https://i.imgur.com/wt04Sbz.png',
    number: 37
  },
  {
    heroName: 'Shadow Shaman',
    race1: 'Troll',
    race1Icon: 'https://i.imgur.com/8Th2eZ9.png',
    race1Ability: 'Voodoo Frenzy',
    race1lvl1: '(2) Trolls: All Trolls gain 35 attack speed',
    race1lvl2: '(4) Trolls: All allies gain an additional 35 attack speed',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Shaman',
    heroClass1Ability: 'Hex',
    heroClasslvl1: '(2) Shaman: Apply Hex to a random enemy unit at the start of each round',
    heroClasslvl2: '',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/YvPL46t.png',
    ability1Icon: 'https://i.imgur.com/OcS6pVw.png',
    ability1Name: 'Hex',
    ability1Target: 'Target: Enemy Unit',
    ability1Duration: 'Duration: 4/6/8',
    ability1Cooldown: 'Cooldown: 10',
    ability1Description: 'Transforms an enemy unit into a harmless chicken, disabling all attacks and abilities for the duration of the effect.',
    ability2Icon: '',
    ability2Name: '',
    cost: '1',
    portrait: 'https://i.imgur.com/vWGguPA.png',
    rank1: 'https://i.imgur.com/Z8ZbywV.png',
    number: 38
  },
  {
    heroName: 'Slardar',
    race1: 'Naga',
    race1Icon: 'https://i.imgur.com/lO6z92w.png',
    race1Ability: 'Scale Armor',
    race1lvl1: '(2) Naga: All allies gain 20 magic resist',
    race1lvl2: '(4) Naga: All allies gain an additional 40 magic resist',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Warrior',
    heroClass1Ability: 'Fortified Armor',
    heroClasslvl1: '(3) Warriors: All Warriors gain 7 armor',
    heroClasslvl2: '(6) Warriors: All Warriors gain an additional 8 armor',
    heroClasslvl3: '(9) Warriors: All Warriors gain an additional 10 armor',
    heroClass1Icon: 'https://i.imgur.com/eat1oWG.png',
    ability1Icon: 'https://i.imgur.com/41CLVSw.png',
    ability1Name: 'Corrosive Haze',
    ability1Target: 'Target: Enemy Units',
    ability1Duration: 'Duration: 20',
    ability1Cooldown: 'Cooldown: 3',
    ability1Description: 'Reduces an enemies armor 15/30/45 and provides True Sight of the targeted unit, revealing invisibility.',
    ability2Icon: '',
    ability2Name: '',
    cost: '2',
    portrait: 'https://i.imgur.com/ZjxawsK.png',
    rank1: 'https://i.imgur.com/4scDdsi.png',
    number: 39
  },
  {
    heroName: 'Slark',
    race1: 'Naga',
    race1Icon: 'https://i.imgur.com/lO6z92w.png',
    race1Ability: 'Scale Armor',
    race1lvl1: '(2) Naga: All allies gain 20 magic resist',
    race1lvl2: '(4) Naga: All allies gain an additional 40 magic resist',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Assassin',
    heroClass1Ability: 'Coup de Grace',
    heroClasslvl1: '(3) Assassins: All Assassins gain a 10% chance to deal a 350% damage critical strike',
    heroClasslvl2: '(6) Assassins: All Assassins gain an additional 20% chance to deal a 350% damage critical strike',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/0r0Ivea.png',
    ability1Icon: 'https://i.imgur.com/eiw3BI9.png',
    ability1Name: 'Shadow Dance',
    ability1Duration: 'Duration: 4 Seconds',
    ability1Cooldown: 'Cooldown: 10/8/6',
    ability1Description: 'Slark hides himself in a cloud of shadows, becoming immune to detection. Attacking will not reveal Slark. Passively, when not visible to the enemy team, Slark gains 30%/40%/50% bonus movement speed and 3%/6%/9% health regeneration.',
    ability2Icon: '',
    ability2Name: '',
    cost: '3',
    portrait: 'https://i.imgur.com/wpVnCfx.png',
    rank1: 'https://i.imgur.com/4EedkHu.png',
    number: 40
  },
  {
    heroName: 'Sniper',
    race1: 'Dwarf',
    race1Icon: 'https://i.imgur.com/J6LcqKh.png',
    race1Ability: 'Take Aim',
    race1lvl1: ' (1) Dwarf: This unit gains 300 attack range',
    race1lvl2: '',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Hunter',
    heroClass1Ability: 'Hunters Pack',
    heroClasslvl1: '(3) Hunters: All Hunters deal 25% more attack damage',
    heroClasslvl2: '(6) Hunters: All Hunters deal an additional 35% more attack damage',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/oD6geML.png',
    ability1Icon: 'https://i.imgur.com/cW1eCPP.png',
    ability1Name: 'Assassinate',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: Enemy Units',
    ability1Damage: 'Damage: 400/600/800',
    ability1Cooldown: 'Cooldown: 10',
    ability1Description: 'Sniper locks onto a random enemy unit and after a 1 second aiming direction fires a devastating shot that deals damage at long range and stuns the target.',
    ability2Icon: '',
    ability2Name: '',
    cost: '3',
    portrait: 'https://i.imgur.com/CGD8D5m.png',
    rank1: 'https://i.imgur.com/njIWyfl.png',
    number: 41
  },
  {
    heroName: 'Techies',
    race1: 'Goblin',
    race1Icon: 'https://i.imgur.com/e2CyWql.png',
    race1Ability: 'Nanobots',
    race1lvl1: '(3) Goblins: Increase Armor and HP Regen by 15 for a random ally',
    race1lvl2: '(6) Goblins: Increase Armor and HP Regen by 15 for all Goblins',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Mech',
    heroClass1Ability: 'Self Repair',
    heroClasslvl1: '(2) Mechs: All Mechs gain 10 HP regeneration',
    heroClasslvl2: '(4) Mechs: All Mechs gain an additional 20 HP regeneration',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/SSphR17.png',
    ability1Icon: 'https://i.imgur.com/2AB2wLI.png',
    ability1Name: 'Explosive Bomb',
    ability1DmgType: 'Type: Physical',
    ability1Target: 'Target: Area of Effect',
    ability1Duration: 'Duration: 3',
    ability1Radius: 'Radius: 600',
    ability1Damage: 'Damage: 700/1100/1500',
    ability1Cooldown: 'Cooldown: 10',
    ability1Description: 'Plants a bomb that detonates after a brief delay, damaging all enemies within its radius.',
    ability2Icon: '',
    ability2Name: '',
    cost: '5',
    portrait: 'https://i.imgur.com/GC40jt5.png',
    rank1: 'https://i.imgur.com/GzXgCLt.png',
    number: 42
  },
  {
    heroName: 'Templar Assassin',
    race1: 'Elf',
    race1Icon: 'https://i.imgur.com/Wy9ES4n.png',
    race1Ability: 'Evasion',
    race1lvl1: '(3) Elves: All Elves gain 25% evasion from incoming attacks',
    race1lvl2: '(6) Elves: All Elves gain an additional 25% evasions from incoming attacks',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Assassin',
    heroClass1Ability: 'Coup de Grace',
    heroClasslvl1: '(3) Assassins: All Assassins gain a 10% chance to deal a 350% damage critical strike',
    heroClasslvl2: '(6) Assassins: All Assassins gain an additional 20% chance to deal a 350% damage critical strike',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/0r0Ivea.png',
    ability1Icon: 'https://i.imgur.com/F9GMIQq.png',
    ability1Name: 'Refraction',
    ability1DmgType: 'Type: Physical',
    ability1Duration: 'Duration: 6',
    ability1Damage: 'Damage: 40/60/80',
    ability1Cooldown: 'Cooldown: 6',
    ability1Description: 'Templar Assassin becomes highly elusive, avoiding damage and gaining a bonus to her damage. The damage and avoidance effects are separate and occur 4/6/8 times per activation.',
    ability2Icon: '',
    ability2Name: '',
    cost: '3',
    portrait: 'https://i.imgur.com/T80yXSM.png',
    rank1: 'https://i.imgur.com/eugDcEb.png',
    number: 43
  },
  {
    heroName: 'Terrorblade',
    race1: 'Demon',
    race1Icon: 'https://i.imgur.com/oSLSl5s.png',
    race1Ability: 'Fel Power',
    race1lvl1: 'Unique: If this unit is the only Demon on your battlefield, it deal an addition 50% pure damage',
    race1lvl2: '',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Demon Hunter',
    heroClass1Ability: 'Soul Split',
    heroClasslvl1: '(1) Demon Hunter: Enemey Demons no longer gain the Fel Power ability bonus',
    heroClasslvl2: '(2) Demon Hunters: All ally Demons keep the Fel Power bonus',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/9O3YD2y.png',
    ability1Icon: 'https://i.imgur.com/BZSKe0f.png',
    ability1Name: 'Metamorphosis',
    ability1DmgType: 'Type: Physical',
    ability1Duration: 'Duration: 60',
    ability1Damage: 'Damage: 50/100/200',
    ability1Cooldown: 'Cooldown: 60',
    ability1Description: 'Terrorblade transforms into a terrible form, gaining 600 bonus attack range, 50/75/100 bonus attack speed and additional bonus damage.',
    ability2Icon: '',
    ability2Name: '',
    cost: '3',
    portrait: 'https://i.imgur.com/FY1uSR4.png',
    rank1: 'https://i.imgur.com/DTRpBag.jpg',
    number: 44
  },
  {
    heroName: 'Tidehunter',
    race1: 'Naga',
    race1Icon: 'https://i.imgur.com/lO6z92w.png',
    race1Ability: 'Scale Armor',
    race1lvl1: '(2) Naga: All allies gain 20 magic resist',
    race1lvl2: '(4) Naga: All allies gain an additional 40 magic resist',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Hunter',
    heroClass1Ability: 'Hunters Pack',
    heroClasslvl1: '(3) Hunters: All Hunters deal 25% more attack damage',
    heroClasslvl2: '(6) Hunters: All Hunters deal an additional 35% more attack damage',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/oD6geML.png',
    ability1Icon: 'https://i.imgur.com/kG7XUdU.png',
    ability1Name: 'Ravage',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: Area of Effect',
    ability1Duration: 'Duration: 2/2.5/3 Seconds',
    ability1Radius: 'Radius: 500/650/800',
    ability1Damage: 'Damage: 150/250/350',
    ability1Cooldown: 'Cooldown: 30',
    ability1Description: 'Ravager slams the ground, causing tentacles to erupt in all directions, damaging and stunning all nearby enemy units. ',
    ability2Icon: '',
    ability2Name: '',
    cost: '5',
    portrait: 'https://i.imgur.com/gJleybw.png',
    rank1: 'https://i.imgur.com/YHxEDWk.png',
    number: 45
  },
  {
    heroName: 'Timbersaw',
    race1: ' Goblin',
    race1Icon: 'https://i.imgur.com/e2CyWql.png',
    race1Ability: '',
    race1lvl1: '(3) Goblins: Increase Armor and HP Regen by 15 for a random ally Goblins: Increase Armor and HP Regen by 15 for a random ally',
    race1lvl2: '(6) Goblins: Increase Armor and HP Regen by 15 for all Goblins',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Mech',
    heroClass1Ability: 'Self Repair',
    heroClasslvl1: '(2) Mechs: All Mechs gain 10 HP regeneration',
    heroClasslvl2: '(4) Mechs: All Mechs gain an additional 20 HP regeneration',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/SSphR17.png',
    ability1Icon: 'https://i.imgur.com/JXffBad.png',
    ability1Name: 'Whirling Death',
    ability1DmgType: 'Type: Pure',
    ability1Radius: 'Radius: 300',
    ability1Damage: 'Damage: 150/200/250',
    ability1Cooldown: 'Cooldown: 6/5/4',
    ability1Description: 'Timbersaw whirls extremely sharp edges, damaging enemies in an area around him.',
    ability2Icon: '',
    ability2Name: '',
    cost: '2',
    portrait: 'https://i.imgur.com/1OsHlPc.png',
    rank1: 'https://i.imgur.com/lPXXgdN.png',
    number: 46
  },
  {
    heroName: 'Tinker',
    race1: 'Goblin',
    race1Icon: 'https://i.imgur.com/e2CyWql.png',
    race1Ability: 'Nanobots',
    race1lvl1: '(3) Goblins: Increase Armor and HP Regen by 15 for a random ally Goblins: Increase Armor and HP Regen by 15 for a random ally',
    race1lvl2: '(6) Goblins: Increase Armor and HP Regen by 15 for all Goblins',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Mech',
    heroClass1Ability: 'Self Repair',
    heroClasslvl1: '(2) Mechs: All Mechs gain 10 HP regeneration',
    heroClasslvl2: '(4) Mechs: All Mechs gain an additional 20 HP regeneration',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/SSphR17.png',
    ability1Icon: 'https://i.imgur.com/E9QQr0H.png',
    ability1Name: 'Heat-Seeking Missile',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: Enemy Units',
    ability1Damage: 'Damage: 200/300/400 per rocket',
    ability1Cooldown: 'Cooldown: 7',
    ability1Description: 'Launches 3 rockets at random enemies.',
    ability2Icon: '',
    ability2Name: '',
    cost: '1',
    portrait: 'https://i.imgur.com/BWK8E6B.png',
    rank1: 'https://i.imgur.com/IkqGx0a.png',
    number: 47
  },
  {
    heroName: 'Tiny',
    race1: 'Elemental',
    race1Icon: 'https://i.imgur.com/yfXfVL9.png',
    race1Ability: 'Elemental Resistance',
    race1lvl1: '(2) Elementals: Elementals have a 30% chance to turn melee attackers into stone for 3 seconds',
    race1lvl2: '(4) Elementals: Allies have a 30% chance to turn melee attackers into stone for 3 seconds',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Warrior',
    heroClass1Ability: 'Fortified Armor',
    heroClasslvl1: '(3) Warriors: All Warriors gain 7 armor',
    heroClasslvl2: '(6) Warriors: All Warriors gain an additional 8 armor',
    heroClasslvl3: '(9) Warriors: All Warriors gain an additional 10 armor',
    heroClass1Icon: 'https://i.imgur.com/eat1oWG.png',
    ability1Icon: 'https://i.imgur.com/kywvyNv.png',
    ability1Name: 'Toss',
    ability1DmgType: 'Type: ',
    ability1Target: 'Target: ',
    ability1Duration: 'Duration: ',
    ability1Radius: 'Radius: ',
    ability1Damage: 'Damage: ',
    ability1Cooldown: 'Cooldown: ',
    ability1Description: '',
    ability2Icon: '',
    ability2Name: '',
    cost: '1',
    portrait: 'https://i.imgur.com/0ec5IX5.png',
    rank1: 'https://i.imgur.com/fj8djit.png',
    number: 48
  },
  {
    heroName: 'Treant Protector',
    race1: 'Elf',
    race1Icon: 'https://i.imgur.com/Wy9ES4n.png',
    race1Ability: 'Evasion',
    race1lvl1: '(3) Elves: All Elves gain 25% evasion from incoming attacks',
    race1lvl2: '(6) Elves: All Elves gain an additional 25% evasions from incoming attacks',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Druid',
    heroClass1Ability: 'Synergy',
    heroClasslvl1: '(2) Druids: Druids only require combining 2 chess pieces to reach level 2',
    heroClasslvl2: '(4) Druids: Druids only require combining 2 level 2 chess pieces to reach level 3',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/wC70fdy.png',
    ability1Icon: 'https://i.imgur.com/IO7isHS.png',
    ability1Name: 'Leech Seed',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: Enemy Units',
    ability1Duration: 'Duration: 5',
    ability1Radius: 'Radius: 400',
    ability1Damage: 'Damage: 30/45/60 per pulse',
    ability1Cooldown: 'Cooldown: 7',
    ability1Description: 'Treant plants a life-sapping seed in an enemy, draining its health while slowing it for 50%. The seed heals nearby allies for the same amount. Pulses 7 times.',
    ability2Icon: '',
    ability2Name: '',
    cost: '2',
    portrait: 'https://i.imgur.com/yG2721e.png',
    rank1: 'https://i.imgur.com/AYXjlMa.png',
    number: 49
  },
  {
    heroName: 'Troll Warlord',
    race1: 'Troll',
    race1Icon: 'https://i.imgur.com/8Th2eZ9.png',
    race1Ability: 'Voodoo Frenzy',
    race1lvl1: '(2) Trolls: All Trolls gain 35 attack speed',
    race1lvl2: '(4) Trolls: All allies gain an additional 35 attack speed',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Warrior',
    heroClass1Ability: 'Fortified Armor',
    heroClasslvl1: '(3) Warriors: All Warriors gain 7 armor',
    heroClasslvl2: '(6) Warriors: All Warriors gain an additional 8 armor',
    heroClasslvl3: '(9) Warriors: All Warriors gain an additional 10 armor',
    heroClass1Icon: 'https://i.imgur.com/eat1oWG.png',
    ability1Icon: 'https://i.imgur.com/IRrOO24.png',
    ability1Name: 'Fervor',
    ability1Cooldown: 'Aura',
    ability1Description: 'With each continuous blow on the same target, Troll Warlord gains 15/20/25 attack speed. Maximum 6/9/12 stacks. If Troll Warlord changes targets, stacks reset to zero.',
    ability2Icon: '',
    ability2Name: '',
    cost: '4',
    portrait: 'https://i.imgur.com/mxXq90f.png',
    rank1: 'https://i.imgur.com/E1XDe0S.png',
    number: 50
  },
  {
    heroName: 'Tusk',
    race1: 'Beast',
    race1Icon: 'https://i.imgur.com/eHGjBh1.png',
    race1Ability: 'Power of the Wild',
    race1lvl1: '(2) Beasts: All allies gain 10% attack damage',
    race1lvl2: '(4) Beasts: All allies gain an additional 15% attack damage',
    race1lvl3: '(6) Beasts: All allies gain an additional 20% attack damage',
    race2: '',
    race2Icon: '',
    heroClass1: 'Warrior',
    heroClass1Ability: 'Fortified Armor',
    heroClasslvl1: '(3) Warriors: All Warriors gain 7 armor',
    heroClasslvl2: '(6) Warriors: All Warriors gain an additional 8 armor',
    heroClasslvl3: '(9) Warriors: All Warriors gain an additional 10 armor',
    heroClass1Icon: 'https://i.imgur.com/eat1oWG.png',
    ability1Icon: 'https://i.imgur.com/9WvznRE.png',
    ability1Name: 'Walrus Punch',
    ability1DmgType: 'Type: Physical',
    ability1Target: 'Target: Enemy Units',
    ability1Damage: 'Damage: 300%/350%/400%',
    ability1Cooldown: 'Cooldown: 7',
    ability1Description: 'Tusk connects with his mighty Walrus Punch, a critical strike so powerful it launches its victim into the air. The victim is slowed 40% for 2 seconds upon landing.',
    ability2Icon: '',
    ability2Name: '',
    cost: '1',
    portrait: 'https://i.imgur.com/wOYddg2.png',
    rank1: 'https://i.imgur.com/c7ISpMw.png',
    number: 51
  },
  {
    heroName: 'Venomancer',
    race1: 'Beast',
    race1Icon: 'https://i.imgur.com/eHGjBh1.png',
    race1Ability: 'Power of the Wild',
    race1lvl1: '(2) Beasts: All allies gain 10% attack damage',
    race1lvl2: '(4) Beasts: All allies gain an additional 15% attack damage',
    race1lvl3: '(6) Beasts: All allies gain an additional 20% attack damage',
    race2: '',
    race2Icon: '',
    heroClass1: 'Warlock',
    heroClass1Ability: 'Life Steal',
    heroClasslvl1: '(3) Warlocks: All allies gain 15% lifesteal',
    heroClasslvl2: '(6) Warlocks: All allies gain an additional 25% lifesteal',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/OngJXn3.png',
    ability1Icon: 'https://i.imgur.com/O0b5c98.png',
    ability1Name: 'Plague Ward',
    ability1DmgType: 'Type: Physical',
    ability1Target: 'Target: -',
    ability1Duration: 'Duration: 60',
    ability1Radius: 'Radius: 100',
    ability1Damage: 'Plague Ward Damage: 75/125/175',
    ability1Cooldown: 'Cooldown: 5',
    ability1Description: 'Summons a Plague Ward beside Venomancer that attacks enemy chess pieces.',
    ability2Icon: '',
    ability2Name: '',
    cost: '3',
    portrait: 'https://i.imgur.com/PxSDzQG.png',
    rank1: 'https://i.imgur.com/cPrrHmx.png',
    number: 52
  },
  {
    heroName: 'Viper',
    race1: 'Dragon',
    race1Icon: 'https://i.imgur.com/ayX9w4V.png',
    race1Ability: 'Attunement',
    race1lvl1: '(3) Dragons: All Dragons start each round with 100 mana',
    race1lvl2: '',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Assassin',
    heroClass1Ability: 'Coup de Grace',
    heroClasslvl1: '(3) Assassins: All Assassins gain a 10% chance to deal a 350% damage critical strike',
    heroClasslvl2: '(6) Assassins: All Assassins gain an additional 20% chance to deal a 350% damage critical strike',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/0r0Ivea.png',
    ability1Icon: 'https://i.imgur.com/fvByAB8.png',
    ability1Name: 'Viper Strike',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: Enemy Units',
    ability1Duration: 'Duration: 5',
    ability1Damage: 'Damage: 150/250/350 per second',
    ability1Cooldown: 'Cooldown: 10/7/4',
    ability1Description: 'Viper slows the targetted enemies movement and attack speed by 40%/60%/80% while also dealing poison damage over time. The slow effect reduces over the poisons duration.',
    ability2Icon: '',
    ability2Name: '',
    cost: '3',
    portrait: 'https://i.imgur.com/Fu00rWZ.png',
    rank1: 'https://i.imgur.com/I0EZaQG.png',
    number: 53
  },
  {
    heroName: 'Windranger',
    race1: 'Elf',
    race1Icon: 'https://i.imgur.com/Wy9ES4n.png',
    race1Ability: 'Evasion',
    race1lvl1: '(3) Elves: All Elves gain 25% evasion from incoming attacks',
    race1lvl2: '(6) Elves: All Elves gain an additional 25% evasions from incoming attacks',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Hunter',
    heroClass1Ability: 'Hunters Pack',
    heroClasslvl1: '(3) Hunters: All Hunters deal 25% more attack damage',
    heroClasslvl2: '(6) Hunters: All Hunters deal an additional 35% more attack damage',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/oD6geML.png',
    ability1Icon: 'https://i.imgur.com/yByhNMb.png',
    ability1Name: 'Powershot',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: AOE',
    ability1Radius: 'Range: 1000',
    ability1Damage: 'Damage: 400/600/800',
    ability1Cooldown: 'Cooldown: 10',
    ability1Description: 'Windranger charges her bow for up to 1 second for a single powerful shot,dealing more damage the longer it is charged. For each enemy that Powershot hits, its damage is reduced by 20%.',
    ability2Icon: '',
    ability2Name: '',
    cost: '3',
    portrait: 'https://i.imgur.com/FMQeLCR.png',
    rank1: 'https://i.imgur.com/kzViJd1.png',
    number: 54
  },
  {
    heroName: 'Witch Doctor',
    race1: 'Troll',
    race1Icon: 'https://i.imgur.com/8Th2eZ9.png',
    race1Ability: 'Voodoo Frenzy',
    race1lvl1: '(2) Trolls: All Trolls gain 35 attack speed',
    race1lvl2: '(4) Trolls: All allies gain an additional 35 attack speed',
    race1lvl3: '',
    race2: '',
    race2Icon: '',
    heroClass1: 'Warlock',
    heroClass1Ability: 'Life Steal',
    heroClasslvl1: '(3) Warlocks: All allies gain 15% lifesteal',
    heroClasslvl2: '(6) Warlocks: All allies gain an additional 25% lifesteal',
    heroClasslvl3: '',
    heroClass1Icon: 'https://i.imgur.com/OngJXn3.png',
    ability1Icon: 'https://i.imgur.com/M0Djpeb.png',
    ability1Name: 'Paralyzing Cask',
    ability1DmgType: 'Type: Magical',
    ability1Target: 'Target: Enemy Units',
    ability1Duration: 'Duration: 1',
    ability1Radius: 'Radius: 1000',
    ability1Damage: 'Damage: 50/75/100',
    ability1Cooldown: 'Cooldown: 10',
    ability1Description: 'Launches a cask of paralyzing powder that ricochets between 3/5/7 enemies, stunning for 1 second and damaging them.',
    ability2Icon: '',
    ability2Name: '',
    cost: '2',
    portrait: 'https://i.imgur.com/P2GeAEx.png',
    rank1: 'https://i.imgur.com/9hG0n45.png',
    number: 55
  }
];
